#nginx_t:

#    image:  malgrat/nginx_tools # tutum/nginx # malgrat/nginx_base:ubuntu1604 # #  #latest  # malgrat/nginx_base:latest # tutum/nginx # 
#    container_name: nginx
#    ports:
#     - "8888:80"
 
##     - "443:443"
#    links:
#     - phpfpm
#     - rabbitmq:rabbitmq
#     - mysql:mysql
#     - memcached:memcached
#nginx_t:
#    image:  malgrat/nginx_base:tutumubuntu_phalcon #malgrat/nginx_tools #malgrat/nginx_base #:tutumubuntu_proto  
#    container_name: nginx_t
#    ports:
#     - "8888:80"
#    links:
#     - phpfpm
#     - rabbitmq:rabbitmq
#     - mysql:mysql
#     - memcached:memcached
#    volumes:
##     - ./nginx/gate.docker:/etc/nginx/sites-available/gate.docker
##     - ./nginx/gate.docker:/etc/nginx/sites-enabled/gate.docker
#     - ./nginx/tools.docker:/etc/nginx/sites-available_tools/tools.docker
#     - ./nginx/nginx_tools.conf:/etc/nginx/nginx.conf
#     - ./nginx/sites-available:/etc/nginx/sites-available
#     - ./nginx/tools.docker:/etc/nginx/sites-enabled_tools/tools.docker
###     - ./nginx/default:/etc/nginx/sites-available/default
###     - ./nginx/default:/etc/nginx/sites-enabled/default
#     - /var/www/ecogate-tools:/var/www/ecogate-tools

#     - ./logs/nginx-error_tools.log:/var/log/nginx/error_tools.log
#     - ./logs/nginx-access_tools.log:/var/log/nginx/access_tools.log
nginx:
    image:  malgrat/nginx_base:tutumubuntu_phalcon # malgrat/nginx_base #tutumubuntu_proto #malgrat/nginx_tools #malgrat/nginx_base #:tutumubuntu_proto  
    container_name: nginx
    ports:
     - "8889:80"
    links:
     - phpfpm
     - rabbitmq:rabbitmq
     - mysql:mysql
     - memcached:memcached
    extra_hosts:
     - "gate.docker:localhost"
    volumes:
     - ./nginx/gate.docker:/etc/nginx/sites-available/gate.docker
     - ./nginx/gate.docker:/etc/nginx/sites-enabled/gate.docker
#     - ./nginx/sites-available:/etc/nginx/sites-available
     - ./nginx_gate/default:/etc/nginx/sites-available/default
     - ./nginx_gate/default:/etc/nginx/sites-enabled/default
     - /var/www/ecogate-proto:/var/www/ecogate-proto
     - ./nginx_gate/nginx-error.log:/var/log/nginx/error.log
     - ./nginx_gate/nginx-access.log:/var/log/nginx/access.log
nginx_tools:
    image:  malgrat/nginx_base:tutumubuntu_phalcon # malgrat/nginx_base #tutumubuntu_proto #malgrat/nginx_tools #malgrat/nginx_base #:tutumubuntu_proto  
    container_name: nginx_tools
    ports:
     - "8888:80"
    links:
     - phpfpm
     - rabbitmq:rabbitmq
     - mysql:mysql
     - memcached:memcached
    volumes:
     - ./nginx/tools.docker:/etc/nginx/sites-available/tools.docker
     - ./nginx/tools.docker:/etc/nginx/sites-enabled/tools.docker
#     - ./nginx/sites-available:/etc/nginx/sites-available
     - ./nginx/default:/etc/nginx/sites-available/default
     - ./nginx/default:/etc/nginx/sites-enabled/default
     - /var/www/ecogate-tools:/var/www/ecogate-tools
     - ./logs/nginx-error.log:/var/log/nginx/error.log
     - ./logs/nginx-access.log:/var/log/nginx/access.log
phpfpm:
    image: malgrat/phpfpm:rdkafka #malgrat/phpfpm:phalcon # majksner/php-fpm # php:fpm
    container_name: phpfpm
    extra_hosts:
#     - "tools.docker:172.17.0.1"
     - "localhost:172.17.0.1"
#     - "gate.docker:172.17.0.1" 
    ports:
        - "9000:9000"
    volumes:
        - /var/www/ecogate-tools:/var/www/ecogate-tools
        - /var/www/ecogate-proto:/var/www/ecogate-proto
mysql:
  image: percona/percona-server:latest
  container_name: mysql_percona
  environment:
    MYSQL_ROOT_PASSWORD: 123456
  ports:
    - "3307:3306"
  volumes:
    # create volumes for use
    - /var/lib/mysql
    # bind mount my local my.cnf
    # - $PWD/my.cnf:/etc/my.cnf
  command:
    # Workaround for no my.cnf in image
    #  - '--user=mysql'
    - '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
#mysql:
#  image: mariadb
#  environment:
#    MYSQL_ROOT_PASSWORD: admin
#  ports:
#    - "5306:3306" 
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: mysql_pma
  restart: always
  links:
    - mysql
  ports:
    - 8183:80
  environment:
    PMA_USER: root
    PMA_PASSWORD: 123456
    PMA_ARBITRARY: 1
rabbitmq:
  image: rabbitmq:3.6.1-management
  container_name: rabbitmq
  ports:
    - "15673:15672"
    - "5673:5672"
memcached:
  image: memcached
  container_name: memcached
  ports:
    - "11212:11211"
#kafka: 
#  image: malgrat/kafka-cluster
#  container_name: kafka
#  links:
#    - nginx
